Repository catenax-ng/tx-portal-backend, pull requests merged in 2022-12, with the labels that each got.

#7 CPLP-1576: Fix notifications naming
  .github/workflows/veracode.yaml
  docker/Dockerfile-notification-service
Labels: bug

#8 CPLP-1828 fix query validating calling users association with application
  src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
  src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/registration/Registration.Service/Controllers/RegistrationController.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
  tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
Labels: bug

#16 Service API Endpoint - Swagger description update
  src/marketplace/Services.Service/Controllers/ServicesController.cs
Labels: documentation

#14 CPLP-1918 edit batch delete job
  src/Portal.Backend.sln
  src/maintenance/Maintenance.App/BatchDeleteService.cs
  tests/maintenance/Maintenance.App.Tests/BatchDeleteServiceTests.cs
  tests/maintenance/Maintenance.App.Tests/Maintenance.App.Tests.csproj
  tests/maintenance/Maintenance.App.Tests/Setup/TestDbFixture.cs
  tests/maintenance/Maintenance.App.Tests/Usings.cs
  tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
Labels: bug

#21 CPLP-1840 post service
  postman/CatenaX Portal Service-local.postman_collection.json
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
  src/marketplace/Offers.Library/Models/OfferingData.cs
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryFakeDbTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
Labels: enhancement, Release 3.0 PR

#35 Defect/cplp-1953-registration-store-address
  src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
Labels: Release 3.0 PR
