Repository catenax-ng/tx-portal-backend, pull requests merged in 2023-03, with the labels that each got.

#239 fix(registration): fix process-creation on application submission
  src/checklist/Checklist.Library/ChecklistCreationService.cs
  src/checklist/Checklist.Library/ChecklistService.cs
  src/checklist/Checklist.Library/IChecklistCreationService.cs
  src/checklist/Checklist.Worker.Library/ProcessExecutor.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IProcessStepRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ProcessStepRepository.cs
  tests/checklist/Checklist.Library.Tests/ChecklistCreationServiceTests.cs
  tests/checklist/Checklist.Library.Tests/ChecklistServiceTests.cs
  tests/checklist/Checklist.Worker.Library.Tests/ProcessExecutorTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/ProcessStepRepositoryTests.cs
Labels: Priority

#222 feature/cplp-2235-conformity-document-type-app-api
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
  src/marketplace/Apps.Service/appsettings.json
  src/marketplace/Offers.Library/Service/IOfferService.cs
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OfferReleaseData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
Labels: Priority

#275 feat(app): extend use cases
  src/marketplace/Apps.Service/ViewModels/AppData.cs
  src/marketplace/Apps.Service/ViewModels/AppDetailResponse.cs
  src/marketplace/Offers.Library/Models/OfferProviderResponse.cs
  src/portalbackend/PortalBackend.DBAccess/Models/AppUseCaseData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailsData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OfferProviderData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
Labels: Priority

#276 fix(service): Put Submit Service
  src/marketplace/Offers.Library/Service/OfferService.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Labels: Priority

#281 feat(migrations): combine migrations to 1.2.0
  src/portalbackend/PortalBackend.Migrations/Migrations/20230309131737_CPLP-1783-ProcessConcurrency.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230309131737_CPLP-1783-ProcessConcurrency.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230317105906_AddMessageToProcessSteps.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230320125008_CPLP-1538-AddCompanyAssignedRolesAudit.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230320140923_CPLP-2195-AddMimeTypeToDocuments.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230320140923_CPLP-2195-AddMimeTypeToDocuments.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230323142107_1.2.0.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230323142107_1.2.0.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
Labels: 1.2.0

#289 bug(appReleaseProcess):post SubmitOfferConsentToAgreements
  src/marketplace/Offers.Library/Service/OfferService.cs
Labels: Priority

#290 feat(appReleaseProcess): Put UpdateAppRelease
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/ViewModels/AppRequestModel.cs
  src/portalbackend/PortalBackend.DBAccess/Models/AppUpdateData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
Labels: Priority, 1.3.0-RC1

#298 feat(services):get company provided service status
  src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
  src/marketplace/Services.Service/Controllers/ServicesController.cs
  src/marketplace/Services.Service/ViewModels/ServiceStatusIdFilter.cs
  src/portalbackend/PortalBackend.DBAccess/Models/AllOfferStatusData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
  tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
Labels: Priority, 1.3.0-RC1

#280 feat(servicerelease):get offer(services) in_review and active state
  src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
  src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
  src/marketplace/Services.Service/ServiceSettings.cs
  src/marketplace/Services.Service/appsettings.json
  src/portalbackend/PortalBackend.DBAccess/Models/InReviewServiceData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
  tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
Labels: Priority, 1.3.0-RC1
