Repository catenax-ng/tx-portal-backend, pull requests merged in 2023-01, with the labels that each got.

#43 CPLP-1966 document json
  src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/IDocumentsBusinessLogic.cs
  src/administration/Administration.Service/Controllers/DocumentsController.cs
  src/portalbackend/PortalBackend.DBAccess/Models/DocumentSeedData.cs
  src/portalbackend/PortalBackend.DBAccess/PortalBackend.DBAccess.csproj
  src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/DocumentsBusinessLogicTests.cs
  tests/administration/Administration.Service.Tests/Controllers/DocumentsControllerTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
Labels: bug, Release 3.0 PR

#46 CPLP-1966 add custom configuration value for document seed data
  src/administration/Administration.Service/BusinessLogic/DocumentSettings.cs
  src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
  src/administration/Administration.Service/Program.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/DocumentsBusinessLogicTests.cs
Labels: bug, enhancement

#50 fix: cplp-1042 - trigger creation
  src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
  src/portalbackend/PortalBackend.PortalEntities/Auditing/EntityTypeBuilderV1Extension.cs
Labels: bug

#53 added batch seeding for all entities
  src/portalbackend/PortalBackend.Migrations/Seeder/BaseEntityBatchSeeder.cs
  src/portalbackend/PortalBackend.Migrations/Seeder/BatchSeeder.cs
  src/portalbackend/PortalBackend.Migrations/Seeder/LanugageSeeder.cs
  src/portalbackend/PortalBackend.Migrations/Seeder/MappingEntityInsertOnlySeeder.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/Country.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/UseCase.cs
  tests/maintenance/Maintenance.App.Tests/Setup/TestDbFixture.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/Setup/TestDbFixture.cs
  tests/shared/Tests.Shared/IntegrationTests/IntegrationTestFactory.cs
Labels: enhancement

#61 DB Seeding_consortia data load offers
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/offer_descriptions.consortia.json
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/offers.consortia.json
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/service_assigned_service_types.consortia.json
Labels: Release 3.0 PR

#63 Db seeding update user roles
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
Labels: Release 3.0 PR

#64 Db seeding update service accounts
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_account_assigned_roles.consortia.json
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_account_assigned_roles.json
Labels: Release 3.0 PR

#69 CPLP-1676 recreate migration
  src/portalbackend/PortalBackend.Migrations/Migrations/20230110073548_CPLP-1676-AddServiceAccountType.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20230110073548_CPLP-1676-AddServiceAccountType.cs
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.consortia.json
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
Labels: bug

#18 feature/cplp-1832-getapplication-companyaddress-refactoring
  postman/CatenaX Portal Registration local.postman_collection.json
  src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/Administration.Service/Controllers/RegistrationController.cs
  src/administration/Administration.Service/Models/CompanyWithAddressData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserRoleWithAddress.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTest.cs
  tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
Labels: Release 3.0 PR

#28 Defect/CPLP-1944-Email-Key-Value-Missing
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
Labels: Release 3.0 PR

#110 CPLP-1965 add ASPNETCORE_URLS to docker of checklist worker
  docker/Dockerfile-checklist-worker
Labels: bug

#111 CPLP-1965 remove hint paths
  src/framework/Framework.Web/Framework.Web.csproj
  src/portalbackend/PortalBackend.PortalEntities/PortalBackend.PortalEntities.csproj
  tests/framework/Framework.ErrorHandling.Tests/Framework.ErrorHandling.Tests.csproj
Labels: bug
